[package]
name = "cosmic-reader"
version = "0.1.0"
edition = "2021"

[dependencies]
#TODO: color_space may not be maintained
color_space = "0.5"
env_logger = "0.11"
log = "0.4"
#TODO: export ttf-parser in fontdb?
ttf-parser = "0.20"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["tokio", "winit"]

[dependencies.lopdf]
git = "https://github.com/J-F-Liu/lopdf.git"

[features]
default = ["wgpu"]
wgpu = ["libcosmic/wgpu"]
